name: CI
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    build-and-test:
        name: Build the project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run eslint
              run: npm run lint
            - name: Test and coverage
              run: npm run test
              env:
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_PORT: ${{ secrets.DB_PORT }}
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DB_NAME: ${{ secrets.DB_NAME }}
                  HASH_SECRET: ${{ secrets.HASH_SECRET }}
                  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
                  JWKS_URI: ${{ secrets.JWKS_URI }}
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                  CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
                  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
                  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
                  CHANGE_EMAIL_OTP_SECRET: ${{ secrets.CHANGE_EMAIL_OTP_SECRET }}
                  CHANGE_PHONE_NUMBER_OTP_SECRET: ${{ secrets.CHANGE_PHONE_NUMBER_OTP_SECRET }}

            - name: Build-ts
              run: npm run build
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    build-and-push-docker:
        name: Build and Push Docker Image
        needs: build-and-test
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: rushimungse/fudo-auth
            IMAGE_TAG: build-${{ github.run_number }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build Docker image
              run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .
            - name: Push Docker image to Docker Hub
              run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
